"""Convert the supplied JPEGs to lossless RGB run data for both C builds.

Pillow is a build dependency only. No decoder or asset files are needed at runtime.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parent.parent
target = root / "build/pm_assets.h"
target.parent.mkdir(exist_ok=True)
temporary = target.with_suffix(".h.tmp")
with temporary.open("w") as out:
    out.write("/* Generated by tools/embed_pm5544.py. Do not edit. */\n")
    for name, filename, expected in (("pm43", "pm5544.jpg", (720, 576)),
                                     ("pm169", "pm5544w.jpg", (1280, 720))):
        with Image.open(root / "assets" / filename) as image:
            assert image.size == expected, (filename, image.size)
            pixels = list(image.convert("RGB").getdata())
        runs = bytearray()
        previous, count = pixels[0], 0
        for pixel in pixels:
            if pixel != previous or count == 65535:
                runs.extend((count & 255, count >> 8, *previous))
                previous, count = pixel, 0
            count += 1
        runs.extend((count & 255, count >> 8, *previous))
        out.write(f"static const unsigned char {name}[] = {{\n")
        for i in range(0, len(runs), 30):
            out.write(",".join(str(x) for x in runs[i:i+30]) + ",\n")
        out.write("};\n")
temporary.replace(target)
