#include "app_info.h"
#include <stdio.h>
#include <string.h>

const char *app_codec_license(void) {
    return
#include "../third_party/openh264/license_text.inc"
    ;
}

const char *app_info_text(void) {
    static char text[4096];
    const char *months = "JanFebMarAprMayJunJulAugSepOctNovDec";
    char month[4] = {0};
    int day, year, number = 1;
    if (sscanf(__DATE__, "%3s %d %d", month, &day, &year) != 3) {
        day = 0; year = 0;
    }
    for (int i=0; i<12; ++i) if (!strncmp(month, months+3*i, 3)) number = i+1;
    snprintf(text, sizeof(text),
        "ATV contest number generator\n"
        "Version: %s\nBuild date: %04d-%02d-%02d\nAuthor: %s\n\n"
        "Purpose\n"
        "Create JPG images for ATV and DATV contests, or a PM5544, PM5644 or FUBK test pattern "
        "with your callsign and Maidenhead locator.\n\n"
        "Getting started\n"
        "Select Contest, PM5544, PM5644 or FUBK and enter your callsign and locator. "
        "Locators can contain 4, 6, 8, 10 or 12 characters. "
        "Then select the aspect ratio and resolution (default 320 x 240).\n\n"
        "Contest mode immediately displays an automatically generated number. "
        "Select New number for another code, or choose Manual entry. "
        "You can select the band, invert colours, use blue/yellow, show the locator and digit sum, "
        "and add a code at the top right. EBU top/bottom adds separate colour bars. Export saves the displayed code.\n\n"
        "In automatic mode, the number changes when the locator square changes "
        "(first six characters); greater precision within the same square keeps the number.\n\n"
        "PM5544 and PM5644 display your callsign and locator in the black panels "
        "of the built-in test pattern. FUBK shows the callsign on the left and six locator characters on the right. "
        "Contest options are disabled for these test patterns.\n\n"
        "PM5644 uses EPROM-derived image tables from PAL-sign (PE5PVB, GPLv3-or-later). "
        "Source: github.com/PE5PVB/PAL-sign; see assets/pm5644 in our source code.\n\n"
        "Use File > Export JPG or the export button. The JPG file "
        "is saved in the application directory, with up to six locator characters "
        "and the resolution in its filename. "
        "Select File > Export as... to choose a directory and filename. "
        "You will be asked to confirm before replacing an existing file.\n\n"
        "Config > Genius level 2 enables File > Export TS test file. "
        "Select DVB-S/S2/T, SR/BW, FEC and pilots or GI; the TS bitrate is calculated (QPSK). "
        "This creates H.264 video without audio using the built-in OpenH264 encoder. "
        "File > DATV UDP output transmits the current image to an IP address and port. "
        "Config > Teletext edits page 100; Save stores the text immediately. "
        "TS and UDP settings include an option to send teletext page 100 alongside EIT. "
        "Start/Stop control transmission; closing also stops it. Check image compares the original with the compressed image without transmitting. "
        "See Info > OpenH264 licence for the library licence.\n\n"
        "Config > Save current settings saves everything to atv-contestnummer.conf "
        "in the application directory. Settings are loaded at startup; UDP remains off.",
        APP_VERSION, year, number, day, APP_AUTHOR);
    return text;
}

const char *app_abbreviations_text(void) {
    return
        "VIDEO AND IMAGE TIMING\n\n"
        "IDR - Instantaneous Decoding Refresh\n"
        "A self-contained H.264 frame that resets prediction references. A receiver can start decoding here once the decoder information is available. The timeline measures how long a complete IDR takes to transmit, including intervening TS overhead.\n\n"
        "GOP - Group Of Pictures\n"
        "A group of video frames. In this app, the GOP setting is the number of frames between IDR frames. At 5 fps with GOP 5, a new IDR starts every 1000 ms in the video timeline. This interval is not the transfer time of one IDR.\n\n"
        "FPS - Frames Per Second\n"
        "The video frame rate. At 5 fps, each frame period is 200 ms. One encoded frame can take several frame periods to transmit if it arrives before its deadline.\n\n"
        "QP - Quantization Parameter\n"
        "Controls H.264 compression strength. A higher QP generally means less detail and fewer bytes. This app tries QP 24 to 48 and checks whether the resulting stream fits. Always inspect small text for readability.\n\n"
        "I-frame - Intra-coded frame\n"
        "A frame coded without referring to other frames for its picture. An IDR frame additionally resets prediction references.\n\n"
        "P-frame - Predictive-coded frame\n"
        "Uses previously decoded reference pictures, so it cannot be decoded independently. For a static test image, these frames are usually much smaller than IDR frames.\n\n"
        "AVC - Advanced Video Coding (H.264)\n"
        "The video compression standard used by this app. OpenH264 is the built-in encoder and preview decoder.\n\n"
        "SPS / PPS - Sequence / Picture Parameter Set\n"
        "H.264 decoder information, such as picture dimensions and coding settings. This app repeats these parameter sets with every IDR.\n\n"
        "TRANSPORT AND CLOCKS\n\n"
        "TS - Transport Stream (MPEG-TS)\n"
        "Carries compressed video and signalling in 188-byte packets. The displayed TS bitrate includes packet headers, tables and null packets, not just video.\n\n"
        "PES - Packetized Elementary Stream\n"
        "Wraps encoded video data with a header and timestamps before it is split into TS packets.\n\n"
        "PID - Packet Identifier\n"
        "A number in each TS packet that identifies its content, such as video, a table or teletext.\n\n"
        "PCR - Program Clock Reference\n"
        "Clock samples used by the receiver to synchronise its transport clock. The app keeps PCR repetition within 100 ms; adding image buffer time does not relax this limit.\n\n"
        "PTS - Presentation Time Stamp\n"
        "Specifies when a decoded picture should be displayed. This is different from the time its final TS packet arrives.\n\n"
        "DTS - Decoding Time Stamp\n"
        "Specifies when a picture should be decoded. This app uses no B-frames and does not need a separate DTS field.\n\n"
        "CBR - Constant Bit Rate\n"
        "A fixed total transport bitrate. Null packets fill capacity not used by video or signalling.\n\n"
        "CPB - Coded Picture Buffer\n"
        "The decoder buffer for compressed video waiting to be decoded. Its capacity depends on the H.264 profile and level. More transport delay cannot provide unlimited decoder capacity.\n\n"
        "UDP - User Datagram Protocol\n"
        "Sends network datagrams without delivery acknowledgement or automatic retransmission. This app sends seven TS packets per datagram: 1316 bytes.\n\n"
        "IP / IPv4 - Internet Protocol / version 4\n"
        "Identifies the destination device by its network address, for example 192.168.1.50. The UDP port identifies the receiving service.\n\n"
        "RF AND MODULATION\n\n"
        "ATV / DATV - Amateur Television / Digital Amateur Television\n"
        "Amateur radio television. DATV uses digitally encoded pictures and digital transmission.\n\n"
        "DVB - Digital Video Broadcasting\n"
        "A family of digital television standards. DVB-S and DVB-S2 describe satellite delivery systems; DVB-T describes terrestrial delivery. Amateurs also use these modulation systems on amateur bands.\n\n"
        "FEC - Forward Error Correction\n"
        "Adds redundancy so the receiver can correct errors. FEC 1/2 has a lower code rate and more redundancy than 3/4, leaving less TS capacity at the same symbol rate. The app filters out choices that cannot meet its PCR timing limit.\n\n"
        "SR - Symbol Rate\n"
        "The number of modulation symbols transmitted per second. 125 ksym/s means 125000 symbols per second, not 125000 video bits per second.\n\n"
        "BW - Bandwidth\n"
        "The channel bandwidth. For the DVB-T settings here, Portsdown SR/BW is expressed in kHz.\n\n"
        "QPSK - Quadrature Phase Shift Keying\n"
        "Modulation with four phase states, carrying two coded bits per symbol. FEC and transmission overhead reduce the usable TS bitrate.\n\n"
        "GI - Guard Interval\n"
        "An interval added to DVB-T symbols to help tolerate delayed signal paths. A longer guard interval reduces useful data capacity.\n\n"
        "RF - Radio Frequency\n"
        "The over-the-air radio signal. The local preview does not simulate RF fading, interference or reception loss.\n\n"
        "SERVICE INFORMATION\n\n"
        "PSI / SI - Program Specific Information / Service Information\n"
        "Tables that describe the programmes, services and network carried by a transport stream.\n\n"
        "PAT - Program Association Table\n"
        "Lists programmes and points to their PMTs.\n\n"
        "PMT - Program Map Table\n"
        "Identifies a programme's video and other component streams, and its PCR PID.\n\n"
        "SDT - Service Description Table\n"
        "Describes services, including their names and providers. This app uses your callsign.\n\n"
        "NIT - Network Information Table\n"
        "Describes a DVB network and its tuning parameters. Receivers can use it for network scanning. This app currently does not transmit a NIT.\n\n"
        "EIT - Event Information Table\n"
        "Carries programme or event information. This app can send station information, including the callsign, locator, city and operator.\n\n"
        "EPG - Electronic Programme Guide\n"
        "The programme guide shown by a receiver, often using information from EIT.\n\n"
        "TDT / UTC - Time and Date Table / Coordinated Universal Time\n"
        "TDT carries UTC date and time. This app sends it when EIT is enabled. UTC is independent of local time zones and daylight saving time.\n\n"
        "OTHER LABELS AND UNITS\n\n"
        "EBU - European Broadcasting Union\n"
        "The EBU top/bottom options add colour bars to the contest image.\n\n"
        "JPG / JPEG - Joint Photographic Experts Group\n"
        "The compressed still-image format used for image export.\n\n"
        "QTH - Station location (radio Q-code)\n"
        "The QTH locator field uses the Maidenhead grid system, for example JO21QK.\n\n"
        "ms / bit/s / ksym/s / kHz\n"
        "Milliseconds / bits per second / thousands of symbols per second / thousands of hertz. 1000 ms is one second; one byte is eight bits.\n\n"
        "Contest marker: 1000 ms is an operator guideline for IDR transfer time, not a universal limit on aircraft-scatter duration. Waiting for the next IDR, receiver lock and display delay are separate.\n";
}
